# Autodesk Fusion 360 Parametric Script - Generated by AI Agent
# Component: Parametric Mounting Bracket (80.0x40.0x4.0 mm)

import adsk.core, adsk.fusion, traceback

def run(context):
    ui = None
    try:
        app = adsk.core.Application.get()
        ui  = app.userInterface
        design = adsk.fusion.Design.cast(app.activeProduct)
        if not design:
            ui.messageBox('Please switch to the Fusion 360 Design workspace.')
            return

        rootComp = design.rootComponent
        sketches = rootComp.sketches
        xyPlane = rootComp.xYConstructionPlane

        # Create base sketch
        sketch = sketches.add(xyPlane)
        lines = sketch.sketchCurves.sketchLines
        lines.addTwoPointRectangle(
            adsk.core.Point3D.create(0, 0, 0),
            adsk.core.Point3D.create(80.0/10.0, 40.0/10.0, 0)
        )

        # Add mounting holes
        circles = sketch.sketchCurves.sketchCircles
        hole_radius_cm = (5.0 / 2.0) / 10.0
        margin_x = 80.0 * 0.15 / 10.0
        center_y = (40.0 / 2.0) / 10.0
        circles.addByCenterRadius(adsk.core.Point3D.create(margin_x, center_y, 0), hole_radius_cm)
        circles.addByCenterRadius(adsk.core.Point3D.create((80.0/10.0) - margin_x, center_y, 0), hole_radius_cm)

        # Extrude base body
        prof = sketch.profiles.item(0)
        extrudes = rootComp.features.extrudeFeatures
        extInput = extrudes.createInput(prof, adsk.fusion.FeatureOperations.NewBodyFeatureOperation)
        distance = adsk.core.ValueInput.createByReal(4.0 / 10.0)
        extInput.setDistanceExtent(False, distance)
        extrudes.add(extInput)

        ui.messageBox('Autodesk Fusion 360: Successfully generated mounting_bracket (80.0x40.0x4.0mm)!')
    except:
        if ui:
            ui.messageBox('Failed:\n' + traceback.format_exc())
